### ISSUE TITLE
Panic Unmarshall json cannot decode empty bytes

### ISSUE THREAD

**Issue by sophoah** [axelarnetwork/axelarate-community#11]
**Describe the bug**
See picture : 
![image](https://user-images.githubusercontent.com/35721420/114205922-63477d00-998d-11eb-966b-76c53219afd5.png)

**To Reproduce**

1. Execute command `axelarcli q bitcoin txInfo {blockhash} {txID}:{voutIdx}`
2. use an incomplete {blockhash}

**Expected behavior**
a clearer and handled error message mentioning the blockhash wasn't correctly unformatted

**Screenshots/Log excerpts**
If applicable, add screenshots or excerpts from the node log to help explain your problem.

**Additional context**
In this case, the copy paste was missing characters but the error wasn't straight forward pointing to me which field had issues
in the test scenario, most likely worth to also try with an incomplete txID and a non numeric voutIdx

**Comment by cgorenflo** [comment]
Thanks for the diligent testing and great bug description! Since it is a non-critical bug, we won't roll out a hotfix for this iteration of the testnet, which would put an additional burden on all participants to synchronize to update their docker containers. However, it has already been addressed on the master branch and it will be fixed in the next testnet iteration!
