### ISSUE TITLE
`404: Not Found` on testnet.mdx

### ISSUE THREAD

**Issue by rootulp** [axelarnetwork/axelarate-community#397]
**Describe the bug**

```
$ ./scripts/setup-node.sh -n testnet
FAILED to run the last command

script cleanup running
FAILED to run the last command

script cleanup running
```

**To Reproduce**

***Example***
1. Clone this repo
2. Run `$ ./scripts/setup-node.sh -n testnet`
3. See the error above

**Expected behavior**
To set up config for testnet

**Screenshots/Log excerpts**
If I run this with verbose logging, I get a bit more info:

```
$ ./scripts/setup-node.sh -n testnet --verbose
+ shift
+ :
+ case "${1-}" in
+ break
+ args=("$@")
+ '[' testnet == mainnet ']'
+ '[' testnet == testnet ']'
+ '[' -z '' ']'
+ chain_id=axelar-testnet-lisbon-3
+ '[' -z '' ']'
+ root_directory=/Users/rootulp/.axelar_testnet
+ '[' -z '' ']'
++ curl -s https://raw.githubusercontent.com/axelarnetwork/axelar-docs/main/pages/resources/testnet.mdx
++ grep axelar-core
++ cut -d '`' -f 4
+++ failure
+++ trap - SIGINT SIGTERM ERR
+++ msg 'FAILED to run the last command'
+++ echo -e 'FAILED to run the last command'
FAILED to run the last command
+++ cleanup
+++ trap - EXIT
+++ msg
+++ echo -e ''

+++ msg 'script cleanup running'
+++ echo -e 'script cleanup running'
script cleanup running
+++ exit 1
+ axelar_core_version=
++ failure
++ trap - SIGINT SIGTERM ERR
++ msg 'FAILED to run the last command'
++ echo -e 'FAILED to run the last command'
FAILED to run the last command
++ cleanup
++ trap - EXIT
++ msg
++ echo -e ''

++ msg 'script cleanup running'
++ echo -e 'script cleanup running'
script cleanup running
++ exit 1
```

Notice the website it is trying to request isn't found

```
$ curl -s https://raw.githubusercontent.com/axelarnetwork/axelar-docs/main/pages/resources/testnet.mdx
404: Not Found%
```

**Comment by kalidax** [comment]
Hi @rootulp 

Thank you for reaching out.

I pushed a [PR](https://github.com/axelarnetwork/axelarate-community/pull/398) to fix the issue.

The issue is due to an error in the path here `https://github.com/axelarnetwork/axelarate-community/blob/main/scripts/setup-node.sh#L97`

A quick fix whould be to modify that line with that code : 
`axelar_core_version="$(curl -s https://raw.githubusercontent.com/axelarnetwork/axelar-docs/main/src/pages/resources/"${network}".mdx | grep axelar-core | cut -d \` -f 4)"`

I added `src` to the path.

We are checking why that path has been modified.

Thanks again.
Kalid

**Comment by rootulp** [comment]
Thanks resolved.
